// Data in Data Grid row format (objects with named properties)
// Formulas reference cells using HyperFormula's A1 notation

export const rowData = [
  {
    id: 1,
    name: 'Greg Black',
    year_1: 4.66,
    year_2: '=B1*1.3',
    average: '=AVERAGE(B1:C1)',
    sum: '=SUM(B1:C1)',
  },
  {
    id: 2,
    name: 'Anne Carpenter',
    year_1: 5.25,
    year_2: '=$B$2*30%',
    average: '=AVERAGE(B2:C2)',
    sum: '=SUM(B2:C2)',
  },
  {
    id: 3,
    name: 'Natalie Dem',
    year_1: 3.59,
    year_2: '=B3*2.7+2+1',
    average: '=AVERAGE(B3:C3)',
    sum: '=SUM(B3:C3)',
  },
  {
    id: 4,
    name: 'John Sieg',
    year_1: 12.51,
    year_2: '=B4*(1.22+1)',
    average: '=AVERAGE(B4:C4)',
    sum: '=SUM(B4:C4)',
  },
  {
    id: 5,
    name: 'Chris Aklips',
    year_1: 7.63,
    year_2: '=B5*1.1*SUM(10,20)+1',
    average: '=AVERAGE(B5:C5)',
    sum: '=SUM(B5:C5)',
  },
  {
    id: 6,
    name: 'Maria Lopez',
    year_1: 9.12,
    year_2: '=B6*1.5',
    average: '=AVERAGE(B6:C6)',
    sum: '=SUM(B6:C6)',
  },
  {
    id: 7,
    name: 'David Chen',
    year_1: 6.78,
    year_2: '=B7*2.1',
    average: '=AVERAGE(B7:C7)',
    sum: '=SUM(B7:C7)',
  },
  {
    id: 8,
    name: 'Sarah Kim',
    year_1: 11.34,
    year_2: '=B8*0.9+3',
    average: '=AVERAGE(B8:C8)',
    sum: '=SUM(B8:C8)',
  },
  {
    id: 9,
    name: 'James Wilson',
    year_1: 8.45,
    year_2: '=B9*1.75',
    average: '=AVERAGE(B9:C9)',
    sum: '=SUM(B9:C9)',
  },
  {
    id: 10,
    name: 'Emma Davis',
    year_1: 5.92,
    year_2: '=B10*2.3-1',
    average: '=AVERAGE(B10:C10)',
    sum: '=SUM(B10:C10)',
  },
  {
    id: 11,
    name: 'Total',
    year_1: '=SUM(B1:B10)',
    year_2: '=SUM(C1:C10)',
    average: '=IF(SUM(D1:D10)>100, "Greater than 100", "Less than 100")',
    sum: '=SUM(E1:E10)',
  },
];
